version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - /root/ssl/:/etc/nginx/ssl/

  app:
    container_name: app
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - storage:/app/tmp/test/csv
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - '27017:27017'
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongo-db:
  storage:
