version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /root/ssl/:/etc/nginx/ssl/
    depends_on:
      - frontend
      - backend

  frontend:
    image: zws33/language-app-frontend:main
    ports:
      - "3000:80"
      
  backend:
    image: zws33/language-app-backend:main
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

  translation-service:
    image: zws33/language-app-translation-service:main
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TRANSLATION_API_KEY: ${DEEPL_KEY}
