version: '3'
services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    command: npm run dev
    ports:
      - "3001:80"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env

  translation-service:
    build:
      context: ./translation-service
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./translation-service/.env
