version: '3'
services:
  app:
    container_name: app
    image: zws33/file-upload-app:latest
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - storage:/app/tmp/test/csv
    env_file:
      - .env
    depends_on:
      - mongo