version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    env_file:
      - ./backend/.env
    depends_on:
      - translation-service

  translation-service:
    build:
      context: ./translation-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./translation-service/.env
