version: '3'
services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    command: npm run dev
    ports:
      - "3001:80"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: language_app
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  translation-service:
    build:
      context: ./translation-service
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./translation-service/.env
