version: '3'
services:
  frontend:
    image: zws33/language-app-frontend:main
    ports:
      - "3000:80"
      
  backend:
    image: zws33/language-app-backend:main
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

  translation_service:
    image: zws33/language-app-translation_service:main
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TRANSLATION_API_KEY: ${DEEPL_KEY}