version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - /root/ssl/:/etc/nginx/ssl/

  app:
    container_name: app
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - /app/node_modules
      - 'storage:/app/tmp/test/csv'
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  mongo-db:
  storage:
