version: '3'
services:
  frontend:
    image: zws33/file-upload-app-frontend:latest
    ports:
      - "3000:80"
  backend:
    image: zws33/file-upload-app-backend:latest
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
      - storage:/app/tmp/test/csv
    env_file:
      - .env
    depends_on:
      - mongo
  translation_service:
    image: zws33/file-upload-app-translation_service:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TRANSLATION_API_KEY: ${DEEPL_KEY}