version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /root/ssl/:/etc/nginx/ssl/
    depends_on:
      - frontend
      - backend
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  backend:
    platform: "linux/amd64"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - storage:/app/tmp/test/csv
    env_file:
      - .env
    depends_on:
      - translation_service

  translation_service:
    build:
      context: ./translation-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TRANSLATION_API_KEY: ${DEEPL_KEY}
