CREATE TABLE language (
    language_code character varying(3) UNIQUE PRIMARY KEY
);

CREATE TABLE word (
    word_id SERIAL PRIMARY KEY,
    word_text character varying(100) NOT NULL UNIQUE,
    language_code character varying(3) NOT NULL REFERENCES language(language_code)
);

CREATE TABLE tag (
    tag_id SERIAL PRIMARY KEY,
    tag_text character varying(500) NOT NULL UNIQUE
);

CREATE TABLE word_tag (
    word_id integer REFERENCES word(word_id),
    tag_id integer REFERENCES tag(tag_id),
    CONSTRAINT word_tag_pkey PRIMARY KEY (word_id, tag_id)
);

CREATE TABLE translation (
    translation_id SERIAL PRIMARY KEY,
    first_word_id integer NOT NULL REFERENCES word(word_id),
    second_word_id integer NOT NULL REFERENCES word(word_id)
);
INSERT INTO language (language_code) VALUES
('ES'),
('EN');

INSERT INTO word (word_text, language_code) VALUES 
('time', 'EN'),
('year', 'EN'),
('people', 'EN'),
('way', 'EN'),
('day', 'EN'),
('man', 'EN'),
('thing', 'EN'),
('woman', 'EN'),
('life', 'EN'),
('child', 'EN'),
('world', 'EN'),
('school', 'EN'),
('state', 'EN'),
('family', 'EN'),
('student', 'EN'),
('group', 'EN'),
('country', 'EN'),
('problem', 'EN'),
('hand', 'EN'),
('part', 'EN'),
('place', 'EN'),
('case', 'EN'),
('week', 'EN'),
('company', 'EN'),
('system', 'EN'),
('program', 'EN'),
('question', 'EN'),
('work', 'EN'),
('government', 'EN'),
('number', 'EN'),
('night', 'EN'),
('point', 'EN'),
('home', 'EN'),
('water', 'EN'),
('room', 'EN'),
('mother', 'EN'),
('area', 'EN'),
('money', 'EN'),
('story', 'EN'),
('fact', 'EN'),
('month', 'EN'),
('lot', 'EN'),
('right', 'EN'),
('study', 'EN'),
('book', 'EN'),
('eye', 'EN'),
('job', 'EN'),
('word', 'EN'),
('business', 'EN'),
('issue', 'EN'),
('side', 'EN'),
('kind', 'EN'),
('head', 'EN'),
('house', 'EN'),
('service', 'EN'),
('friend', 'EN'),
('father', 'EN'),
('power', 'EN'),
('hour', 'EN'),
('game', 'EN'),
('line', 'EN'),
('end', 'EN'),
('member', 'EN'),
('law', 'EN'),
('car', 'EN'),
('city', 'EN'),
('community', 'EN'),
('name', 'EN'),
('president', 'EN'),
('team', 'EN'),
('minute', 'EN'),
('idea', 'EN'),
('kid', 'EN'),
('body', 'EN'),
('information', 'EN'),
('back', 'EN'),
('parent', 'EN'),
('face', 'EN'),
('others', 'EN'),
('level', 'EN'),
('office', 'EN'),
('door', 'EN'),
('health', 'EN'),
('person', 'EN'),
('art', 'EN'),
('war', 'EN'),
('history', 'EN'),
('party', 'EN'),
('result', 'EN'),
('change', 'EN'),
('morning', 'EN'),
('reason', 'EN'),
('research', 'EN'),
('girl', 'EN'),
('guy', 'EN'),
('moment', 'EN'),
('air', 'EN'),
('teacher', 'EN'),
('force', 'EN'),
('education', 'EN');

INSERT INTO word (word_text, language_code) VALUES
('tiempo', 'ES'),
('año', 'ES'),
('gente', 'ES'),
('manera', 'ES'),
('día', 'ES'),
('hombre', 'ES'),
('cosa', 'ES'),
('mujer', 'ES'),
('vida', 'ES'),
('niño', 'ES'),
('mundo', 'ES'),
('escuela', 'ES'),
('estado', 'ES'),
('familia', 'ES'),
('estudiante', 'ES'),
('grupo', 'ES'),
('país', 'ES'),
('problema', 'ES'),
('mano', 'ES'),
('parte', 'ES'),
('lugar', 'ES'),
('caso', 'ES'),
('semana', 'ES'),
('empresa', 'ES'),
('sistema', 'ES'),
('programa', 'ES'),
('pregunta', 'ES'),
('trabajo', 'ES'),
('gobierno', 'ES'),
('número', 'ES'),
('noche', 'ES'),
('punto', 'ES'),
('hogar', 'ES'),
('agua', 'ES'),
('habitación', 'ES'),
('madre', 'ES'),
('área', 'ES'),
('dinero', 'ES'),
('historia', 'ES'),
('hecho', 'ES'),
('mes', 'ES'),
('lote', 'ES'),
('derecho', 'ES'),
('estudio', 'ES'),
('libro', 'ES'),
('ojo', 'ES'),
('trabajo', 'ES'),
('palabra', 'ES'),
('negocio', 'ES'),
('asunto', 'ES'),
('lado', 'ES'),
('tipo', 'ES'),
('cabeza', 'ES'),
('casa', 'ES'),
('servicio', 'ES'),
('amigo', 'ES'),
('padre', 'ES'),
('poder', 'ES'),
('hora', 'ES'),
('juego', 'ES'),
('línea', 'ES'),
('fin', 'ES'),
('miembro', 'ES'),
('ley', 'ES'),
('coche', 'ES'),
('ciudad', 'ES'),
('comunidad', 'ES'),
('nombre', 'ES'),
('presidente', 'ES'),
('equipo', 'ES'),
('minuto', 'ES'),
('idea', 'ES'),
('niño', 'ES'),
('cuerpo', 'ES'),
('información', 'ES'),
('espalda', 'ES'),
('padre', 'ES'),
('cara', 'ES'),
('otros', 'ES'),
('nivel', 'ES'),
('oficina', 'ES'),
('puerta', 'ES'),
('salud', 'ES'),
('persona', 'ES'),
('arte', 'ES'),
('guerra', 'ES'),
('historia', 'ES'),
('partido', 'ES'),
('resultado', 'ES'),
('cambio', 'ES'),
('mañana', 'ES'),
('razón', 'ES'),
('investigación', 'ES'),
('chica', 'ES'),
('chico', 'ES'),
('momento', 'ES'),
('aire', 'ES'),
('profesor', 'ES'),
('fuerza', 'ES'),
('educación', 'ES');

DO
$$
BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO translation (first_word_id, second_word_id) VALUES (i, i + 100);
    END LOOP;
END;
$$