
name: Build and publish image

on:
  push:
    branches: [ main ]

jobs:
  check:
    
    runs-on: ubuntu-latest
    outputs:
      hasChanges: ${{steps.check_files.outputs.hasChanges}}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: check modified files
        id: check_files
        run: |
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
          echo $file
          if [[ $file == frontend/* ]]; then
              echo "frontend files changed. Setting build trigger variable"
              echo "hasChanges=true" >> $GITHUB_OUTPUT
              break
          fi
          done < files.txt
  
  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.hasChanges == 'true'
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: zws33/language-app-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          
    