name: Docker Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Determine changed folders
        id: changed-files
        run: echo "::set-output name=folders::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^/backend/' | cut -d/ -f1 | uniq)"

      - name: Build and publish Docker images
        if: ${{ steps.changed-files.outputs.folders != '' }}
        run: |
          for folder in ${{ steps.changed-files.outputs.folders }}; do
            docker build -t zws33/file-upload-app:$folder $folder
            docker push zws33/file-upload-app:$folder
          done
